version: "3.7"
services:

  postgres:
    image: postgres:14.0
    container_name: wbpostgres
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - /home/deus/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    networks:
      - wbnet

  migrate:
        image: migrate/migrate
        container_name: migratewbdb
        networks:
            - wbnet
        volumes:
            - ./migrations:/migrations
        command: ["-path", "/migrations", "-database",  "postgres://wbuser:wb@postgres/wbl0db?sslmode=disable", "up"]
        links:
            - postgres

  # nats-streaming:
  #   image: nats-streaming
  #   container_name: wbnats
  #   command:
  #     - "-store"
  #     - file
  #     - "-dir"
  #     - /data/msg
  #   volumes:
  #     - "./natsstore:/data"
  #   ports:
  #     - "4222:4222"
  #     - "8222:8222"
  #   networks:
  #     - wbnet

  rmq:
      # You can access it by visiting http://localhost:15672 in a browser with the default
      # username and password of guest / guest
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - testrmq:/var/lib/rabbitmq
    networks:
      - wbnet

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - wbnet

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
        - wbnet


  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - wbnet

  redis:
    image: "redis:alpine"
    container_name: wbcache
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - wbnet


networks:
  wbnet:
volumes:
  testrmq:
